# Generated by Django 4.1 on 2022-08-11 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('slug_url', models.SlugField(blank=True, help_text='a-bite-of-python', max_length=200, null=True)),
                ('book_link', models.CharField(max_length=2083)),
                ('image', models.ImageField(upload_to='media/')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cateogry', models.ManyToManyField(to='onlinebooks.category')),
            ],
        ),
    ]
