# Generated by Django 4.1 on 2022-09-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='../static/onlinebooks/img/default.png', upload_to='../static/onlinebooks/img/'),
        ),
    ]
